name: understanding contexts
on:
    push:
        branches:
            - main
env:
    GLOBAL_ENV_VAR: learning thoughts global
    ORG_NAME: xyz limited
jobs:
    context-job:
        runs-on: ubuntu-latest
        env:
            JOB_ENV_VAR: learning thoughts job
            ORG_NAME: abc limited
        steps:
            - name: steps example
              env:
                STEP_ENV_VAR: Learning thoughts step
              run: echo '${{env.GLOBAL_ENV_VAR}} ${{env.JOB_ENV_VAR}} ${{env.STEP_ENV_VAR}}'
            - env:
                ORG_NAME: 123 limited
              run: echo '${{env.ORG_NAME}}'
    vars-job:
        runs-on: ubuntu-latest
        steps:
          - name: ptint vars
            run: echo 'token = ${{secrets.TOKEN}} user = ${{vars.USERNAME}}'